namespace GUI.folderTinhTrangPhong
{
    partial class HoaDon
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery1 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column1 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression1 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table1 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column2 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression2 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column3 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression3 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery2 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column4 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression4 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table2 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column5 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression5 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column6 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression6 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column7 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression7 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column8 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression8 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column9 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression9 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery3 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column10 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression10 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table3 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column11 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression11 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column12 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression12 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column13 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression13 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column14 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression14 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery4 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column15 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression15 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table4 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column16 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression16 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column17 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression17 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column18 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression18 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column19 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression19 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column20 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression20 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery5 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column21 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression21 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table5 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column22 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression22 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column23 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression23 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column24 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression24 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column25 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression25 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column26 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression26 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery6 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column27 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression27 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table6 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column28 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression28 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column29 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression29 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column30 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression30 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column31 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression31 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column32 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression32 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column33 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression33 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column34 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression34 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery7 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column35 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression35 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table7 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column36 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression36 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column37 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression37 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column38 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression38 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column39 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression39 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column40 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression40 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column41 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression41 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column42 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression42 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery8 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column43 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression43 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table8 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column44 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression44 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column45 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression45 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column46 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression46 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery9 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column47 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression47 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table9 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column48 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression48 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery10 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column49 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression49 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table10 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column50 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression50 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column51 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression51 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column52 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression52 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column53 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression53 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column54 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression54 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column55 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression55 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column56 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression56 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column57 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression57 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery11 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column58 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression58 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table11 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column59 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression59 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery12 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column60 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression60 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table12 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column61 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression61 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery13 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column62 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression62 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table13 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column63 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression63 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column64 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression64 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery14 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column65 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression65 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table14 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column66 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression66 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column67 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression67 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column68 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression68 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery15 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column69 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression69 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table15 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column70 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression70 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column71 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression71 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column72 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression72 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column73 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression73 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column74 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression74 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery16 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column75 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression75 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table16 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column76 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression76 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column77 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression77 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column78 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression78 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column79 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression79 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery17 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column80 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression80 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table17 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column81 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression81 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column82 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression82 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column83 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression83 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery18 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column84 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression84 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table18 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column85 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression85 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column86 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression86 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column87 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression87 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column88 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression88 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery19 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column89 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression89 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table19 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column90 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression90 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery20 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column91 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression91 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table20 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column92 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression92 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery21 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column93 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression93 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table21 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column94 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression94 = new DevExpress.DataAccess.Sql.ColumnExpression();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(HoaDon));
            this.Detail = new DevExpress.XtraReports.UI.DetailBand();
            this.TopMargin = new DevExpress.XtraReports.UI.TopMarginBand();
            this.xrLabel1 = new DevExpress.XtraReports.UI.XRLabel();
            this.BottomMargin = new DevExpress.XtraReports.UI.BottomMarginBand();
            this.sqlDataSource1 = new DevExpress.DataAccess.Sql.SqlDataSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            // 
            // Detail
            // 
            this.Detail.HeightF = 100F;
            this.Detail.MultiColumn.Mode = DevExpress.XtraReports.UI.MultiColumnMode.UseColumnCount;
            this.Detail.Name = "Detail";
            this.Detail.Padding = new DevExpress.XtraPrinting.PaddingInfo(0, 0, 0, 0, 100F);
            this.Detail.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
            // 
            // TopMargin
            // 
            this.TopMargin.Controls.AddRange(new DevExpress.XtraReports.UI.XRControl[] {
            this.xrLabel1});
            this.TopMargin.HeightF = 100F;
            this.TopMargin.Name = "TopMargin";
            this.TopMargin.Padding = new DevExpress.XtraPrinting.PaddingInfo(0, 0, 0, 0, 100F);
            this.TopMargin.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
            // 
            // xrLabel1
            // 
            this.xrLabel1.Font = new System.Drawing.Font("Segoe UI", 20F);
            this.xrLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.xrLabel1.LocationFloat = new DevExpress.Utils.PointFloat(219.1667F, 10F);
            this.xrLabel1.Name = "xrLabel1";
            this.xrLabel1.Padding = new DevExpress.XtraPrinting.PaddingInfo(2, 2, 0, 0, 100F);
            this.xrLabel1.SizeF = new System.Drawing.SizeF(187.5F, 52.33332F);
            this.xrLabel1.StylePriority.UseFont = false;
            this.xrLabel1.StylePriority.UseForeColor = false;
            this.xrLabel1.StylePriority.UseTextAlignment = false;
            this.xrLabel1.Text = "HÓA ĐƠN";
            this.xrLabel1.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
            // 
            // BottomMargin
            // 
            this.BottomMargin.HeightF = 100F;
            this.BottomMargin.Name = "BottomMargin";
            this.BottomMargin.Padding = new DevExpress.XtraPrinting.PaddingInfo(0, 0, 0, 0, 100F);
            this.BottomMargin.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
            // 
            // sqlDataSource1
            // 
            this.sqlDataSource1.ConnectionName = "localhost_quanlykaraoke_Connection 1";
            this.sqlDataSource1.Name = "sqlDataSource1";
            columnExpression1.ColumnName = "MaDatPhong";
            table1.Name = "datphong";
            columnExpression1.Table = table1;
            column1.Expression = columnExpression1;
            columnExpression2.ColumnName = "ThoiGianDatPhong";
            columnExpression2.Table = table1;
            column2.Expression = columnExpression2;
            columnExpression3.ColumnName = "SoTienDatTruoc";
            columnExpression3.Table = table1;
            column3.Expression = columnExpression3;
            selectQuery1.Columns.Add(column1);
            selectQuery1.Columns.Add(column2);
            selectQuery1.Columns.Add(column3);
            selectQuery1.Name = "datphong";
            selectQuery1.Tables.Add(table1);
            columnExpression4.ColumnName = "MaDV";
            table2.Name = "dichvu";
            columnExpression4.Table = table2;
            column4.Expression = columnExpression4;
            columnExpression5.ColumnName = "TenDV";
            columnExpression5.Table = table2;
            column5.Expression = columnExpression5;
            columnExpression6.ColumnName = "DonGia";
            columnExpression6.Table = table2;
            column6.Expression = columnExpression6;
            columnExpression7.ColumnName = "DonVi";
            columnExpression7.Table = table2;
            column7.Expression = columnExpression7;
            columnExpression8.ColumnName = "MaLDV";
            columnExpression8.Table = table2;
            column8.Expression = columnExpression8;
            columnExpression9.ColumnName = "HinhAnhDV";
            columnExpression9.Table = table2;
            column9.Expression = columnExpression9;
            selectQuery2.Columns.Add(column4);
            selectQuery2.Columns.Add(column5);
            selectQuery2.Columns.Add(column6);
            selectQuery2.Columns.Add(column7);
            selectQuery2.Columns.Add(column8);
            selectQuery2.Columns.Add(column9);
            selectQuery2.Name = "dichvu";
            selectQuery2.Tables.Add(table2);
            columnExpression10.ColumnName = "MaDichVuDatPhong";
            table3.Name = "dichvudatphong";
            columnExpression10.Table = table3;
            column10.Expression = columnExpression10;
            columnExpression11.ColumnName = "MaDichVu";
            columnExpression11.Table = table3;
            column11.Expression = columnExpression11;
            columnExpression12.ColumnName = "SoLuong";
            columnExpression12.Table = table3;
            column12.Expression = columnExpression12;
            columnExpression13.ColumnName = "Gia";
            columnExpression13.Table = table3;
            column13.Expression = columnExpression13;
            columnExpression14.ColumnName = "MaDatPhong";
            columnExpression14.Table = table3;
            column14.Expression = columnExpression14;
            selectQuery3.Columns.Add(column10);
            selectQuery3.Columns.Add(column11);
            selectQuery3.Columns.Add(column12);
            selectQuery3.Columns.Add(column13);
            selectQuery3.Columns.Add(column14);
            selectQuery3.Name = "dichvudatphong";
            selectQuery3.Tables.Add(table3);
            columnExpression15.ColumnName = "MaDVP";
            table4.Name = "dichvuphong";
            columnExpression15.Table = table4;
            column15.Expression = columnExpression15;
            columnExpression16.ColumnName = "MaThuePhong";
            columnExpression16.Table = table4;
            column16.Expression = columnExpression16;
            columnExpression17.ColumnName = "MaDV";
            columnExpression17.Table = table4;
            column17.Expression = columnExpression17;
            columnExpression18.ColumnName = "ThoiGian";
            columnExpression18.Table = table4;
            column18.Expression = columnExpression18;
            columnExpression19.ColumnName = "SoLuong";
            columnExpression19.Table = table4;
            column19.Expression = columnExpression19;
            columnExpression20.ColumnName = "Gia";
            columnExpression20.Table = table4;
            column20.Expression = columnExpression20;
            selectQuery4.Columns.Add(column15);
            selectQuery4.Columns.Add(column16);
            selectQuery4.Columns.Add(column17);
            selectQuery4.Columns.Add(column18);
            selectQuery4.Columns.Add(column19);
            selectQuery4.Columns.Add(column20);
            selectQuery4.Name = "dichvuphong";
            selectQuery4.Tables.Add(table4);
            columnExpression21.ColumnName = "MaDonGiaPhong";
            table5.Name = "dongia_loaiphong";
            columnExpression21.Table = table5;
            column21.Expression = columnExpression21;
            columnExpression22.ColumnName = "MaLoaiPhong";
            columnExpression22.Table = table5;
            column22.Expression = columnExpression22;
            columnExpression23.ColumnName = "GioBatDau";
            columnExpression23.Table = table5;
            column23.Expression = columnExpression23;
            columnExpression24.ColumnName = "GioKetThuc";
            columnExpression24.Table = table5;
            column24.Expression = columnExpression24;
            columnExpression25.ColumnName = "DonGia";
            columnExpression25.Table = table5;
            column25.Expression = columnExpression25;
            columnExpression26.ColumnName = "Thu";
            columnExpression26.Table = table5;
            column26.Expression = columnExpression26;
            selectQuery5.Columns.Add(column21);
            selectQuery5.Columns.Add(column22);
            selectQuery5.Columns.Add(column23);
            selectQuery5.Columns.Add(column24);
            selectQuery5.Columns.Add(column25);
            selectQuery5.Columns.Add(column26);
            selectQuery5.Name = "dongia_loaiphong";
            selectQuery5.Tables.Add(table5);
            columnExpression27.ColumnName = "MaHoaDon";
            table6.Name = "hoadon";
            columnExpression27.Table = table6;
            column27.Expression = columnExpression27;
            columnExpression28.ColumnName = "MaNhanVienThanhToan";
            columnExpression28.Table = table6;
            column28.Expression = columnExpression28;
            columnExpression29.ColumnName = "TongTienThanhToan";
            columnExpression29.Table = table6;
            column29.Expression = columnExpression29;
            columnExpression30.ColumnName = "NgayThanhToan";
            columnExpression30.Table = table6;
            column30.Expression = columnExpression30;
            columnExpression31.ColumnName = "SoTienKhuyenMai";
            columnExpression31.Table = table6;
            column31.Expression = columnExpression31;
            columnExpression32.ColumnName = "GhiChu";
            columnExpression32.Table = table6;
            column32.Expression = columnExpression32;
            columnExpression33.ColumnName = "MaKH";
            columnExpression33.Table = table6;
            column33.Expression = columnExpression33;
            columnExpression34.ColumnName = "TienTraTruoc";
            columnExpression34.Table = table6;
            column34.Expression = columnExpression34;
            selectQuery6.Columns.Add(column27);
            selectQuery6.Columns.Add(column28);
            selectQuery6.Columns.Add(column29);
            selectQuery6.Columns.Add(column30);
            selectQuery6.Columns.Add(column31);
            selectQuery6.Columns.Add(column32);
            selectQuery6.Columns.Add(column33);
            selectQuery6.Columns.Add(column34);
            selectQuery6.Name = "hoadon";
            selectQuery6.Tables.Add(table6);
            columnExpression35.ColumnName = "MaKH";
            table7.Name = "khachhang";
            columnExpression35.Table = table7;
            column35.Expression = columnExpression35;
            columnExpression36.ColumnName = "TenKH";
            columnExpression36.Table = table7;
            column36.Expression = columnExpression36;
            columnExpression37.ColumnName = "CMND";
            columnExpression37.Table = table7;
            column37.Expression = columnExpression37;
            columnExpression38.ColumnName = "SDT";
            columnExpression38.Table = table7;
            column38.Expression = columnExpression38;
            columnExpression39.ColumnName = "DiaChi";
            columnExpression39.Table = table7;
            column39.Expression = columnExpression39;
            columnExpression40.ColumnName = "MaLoaiKH";
            columnExpression40.Table = table7;
            column40.Expression = columnExpression40;
            columnExpression41.ColumnName = "DiemTichLuy";
            columnExpression41.Table = table7;
            column41.Expression = columnExpression41;
            columnExpression42.ColumnName = "TongTienTichLuy";
            columnExpression42.Table = table7;
            column42.Expression = columnExpression42;
            selectQuery7.Columns.Add(column35);
            selectQuery7.Columns.Add(column36);
            selectQuery7.Columns.Add(column37);
            selectQuery7.Columns.Add(column38);
            selectQuery7.Columns.Add(column39);
            selectQuery7.Columns.Add(column40);
            selectQuery7.Columns.Add(column41);
            selectQuery7.Columns.Add(column42);
            selectQuery7.Name = "khachhang";
            selectQuery7.Tables.Add(table7);
            columnExpression43.ColumnName = "MaKhoangThoiGian";
            table8.Name = "khoangthoigiantrongtuna";
            columnExpression43.Table = table8;
            column43.Expression = columnExpression43;
            columnExpression44.ColumnName = "GioBatDau";
            columnExpression44.Table = table8;
            column44.Expression = columnExpression44;
            columnExpression45.ColumnName = "GioKetThuc";
            columnExpression45.Table = table8;
            column45.Expression = columnExpression45;
            columnExpression46.ColumnName = "NgayTrongTuan";
            columnExpression46.Table = table8;
            column46.Expression = columnExpression46;
            selectQuery8.Columns.Add(column43);
            selectQuery8.Columns.Add(column44);
            selectQuery8.Columns.Add(column45);
            selectQuery8.Columns.Add(column46);
            selectQuery8.Name = "khoangthoigiantrongtuna";
            selectQuery8.Tables.Add(table8);
            columnExpression47.ColumnName = "MaLDV";
            table9.Name = "loaidichvu";
            columnExpression47.Table = table9;
            column47.Expression = columnExpression47;
            columnExpression48.ColumnName = "TenLDV";
            columnExpression48.Table = table9;
            column48.Expression = columnExpression48;
            selectQuery9.Columns.Add(column47);
            selectQuery9.Columns.Add(column48);
            selectQuery9.Name = "loaidichvu";
            selectQuery9.Tables.Add(table9);
            columnExpression49.ColumnName = "MaLoaiKH";
            table10.Name = "loaikhachhang";
            columnExpression49.Table = table10;
            column49.Expression = columnExpression49;
            columnExpression50.ColumnName = "TenLoaiKH";
            columnExpression50.Table = table10;
            column50.Expression = columnExpression50;
            columnExpression51.ColumnName = "PhanTramGiamGia";
            columnExpression51.Table = table10;
            column51.Expression = columnExpression51;
            columnExpression52.ColumnName = "SoTienGiamGiaToiThieu";
            columnExpression52.Table = table10;
            column52.Expression = columnExpression52;
            columnExpression53.ColumnName = "SoTienGiamGiaToiDa";
            columnExpression53.Table = table10;
            column53.Expression = columnExpression53;
            columnExpression54.ColumnName = "SoDiemDeDatDuoc";
            columnExpression54.Table = table10;
            column54.Expression = columnExpression54;
            columnExpression55.ColumnName = "PhanTramGiamGia_SinhNhat";
            columnExpression55.Table = table10;
            column55.Expression = columnExpression55;
            columnExpression56.ColumnName = "SoTienGiamGiaToiThieu_SinhNhat";
            columnExpression56.Table = table10;
            column56.Expression = columnExpression56;
            columnExpression57.ColumnName = "SoTienGiamGiaToiDa_SinhNhat";
            columnExpression57.Table = table10;
            column57.Expression = columnExpression57;
            selectQuery10.Columns.Add(column49);
            selectQuery10.Columns.Add(column50);
            selectQuery10.Columns.Add(column51);
            selectQuery10.Columns.Add(column52);
            selectQuery10.Columns.Add(column53);
            selectQuery10.Columns.Add(column54);
            selectQuery10.Columns.Add(column55);
            selectQuery10.Columns.Add(column56);
            selectQuery10.Columns.Add(column57);
            selectQuery10.Name = "loaikhachhang";
            selectQuery10.Tables.Add(table10);
            columnExpression58.ColumnName = "MaLP";
            table11.Name = "loaiphong";
            columnExpression58.Table = table11;
            column58.Expression = columnExpression58;
            columnExpression59.ColumnName = "TenLoaiPhong";
            columnExpression59.Table = table11;
            column59.Expression = columnExpression59;
            selectQuery11.Columns.Add(column58);
            selectQuery11.Columns.Add(column59);
            selectQuery11.Name = "loaiphong";
            selectQuery11.Tables.Add(table11);
            columnExpression60.ColumnName = "MaLoaiTaiKhoan";
            table12.Name = "loaitaikhoan";
            columnExpression60.Table = table12;
            column60.Expression = columnExpression60;
            columnExpression61.ColumnName = "TenLoaiTaiKhoan";
            columnExpression61.Table = table12;
            column61.Expression = columnExpression61;
            selectQuery12.Columns.Add(column60);
            selectQuery12.Columns.Add(column61);
            selectQuery12.Name = "loaitaikhoan";
            selectQuery12.Tables.Add(table12);
            columnExpression62.ColumnName = "idlog";
            table13.Name = "log";
            columnExpression62.Table = table13;
            column62.Expression = columnExpression62;
            columnExpression63.ColumnName = "MaNhanVien";
            columnExpression63.Table = table13;
            column63.Expression = columnExpression63;
            columnExpression64.ColumnName = "ChiTiet";
            columnExpression64.Table = table13;
            column64.Expression = columnExpression64;
            selectQuery13.Columns.Add(column62);
            selectQuery13.Columns.Add(column63);
            selectQuery13.Columns.Add(column64);
            selectQuery13.Name = "log";
            selectQuery13.Tables.Add(table13);
            columnExpression65.ColumnName = "MaNhanVien";
            table14.Name = "nhanvien";
            columnExpression65.Table = table14;
            column65.Expression = columnExpression65;
            columnExpression66.ColumnName = "TenNhanVien";
            columnExpression66.Table = table14;
            column66.Expression = columnExpression66;
            columnExpression67.ColumnName = "DiaChi";
            columnExpression67.Table = table14;
            column67.Expression = columnExpression67;
            columnExpression68.ColumnName = "SDT";
            columnExpression68.Table = table14;
            column68.Expression = columnExpression68;
            selectQuery14.Columns.Add(column65);
            selectQuery14.Columns.Add(column66);
            selectQuery14.Columns.Add(column67);
            selectQuery14.Columns.Add(column68);
            selectQuery14.Name = "nhanvien";
            selectQuery14.Tables.Add(table14);
            columnExpression69.ColumnName = "MaPhong";
            table15.Name = "phong";
            columnExpression69.Table = table15;
            column69.Expression = columnExpression69;
            columnExpression70.ColumnName = "TenPhong";
            columnExpression70.Table = table15;
            column70.Expression = columnExpression70;
            columnExpression71.ColumnName = "MaTinhTrangPhong";
            columnExpression71.Table = table15;
            column71.Expression = columnExpression71;
            columnExpression72.ColumnName = "MaLoaiPhong";
            columnExpression72.Table = table15;
            column72.Expression = columnExpression72;
            columnExpression73.ColumnName = "GhiChu";
            columnExpression73.Table = table15;
            column73.Expression = columnExpression73;
            columnExpression74.ColumnName = "Tang";
            columnExpression74.Table = table15;
            column74.Expression = columnExpression74;
            selectQuery15.Columns.Add(column69);
            selectQuery15.Columns.Add(column70);
            selectQuery15.Columns.Add(column71);
            selectQuery15.Columns.Add(column72);
            selectQuery15.Columns.Add(column73);
            selectQuery15.Columns.Add(column74);
            selectQuery15.Name = "phong";
            selectQuery15.Tables.Add(table15);
            columnExpression75.ColumnName = "MaTaiKhoan";
            table16.Name = "taikhoan";
            columnExpression75.Table = table16;
            column75.Expression = columnExpression75;
            columnExpression76.ColumnName = "TenDangNhap";
            columnExpression76.Table = table16;
            column76.Expression = columnExpression76;
            columnExpression77.ColumnName = "MatKhau";
            columnExpression77.Table = table16;
            column77.Expression = columnExpression77;
            columnExpression78.ColumnName = "LoaiTaiKhoan";
            columnExpression78.Table = table16;
            column78.Expression = columnExpression78;
            columnExpression79.ColumnName = "MaNhanVien";
            columnExpression79.Table = table16;
            column79.Expression = columnExpression79;
            selectQuery16.Columns.Add(column75);
            selectQuery16.Columns.Add(column76);
            selectQuery16.Columns.Add(column77);
            selectQuery16.Columns.Add(column78);
            selectQuery16.Columns.Add(column79);
            selectQuery16.Name = "taikhoan";
            selectQuery16.Tables.Add(table16);
            columnExpression80.ColumnName = "MaThamSo";
            table17.Name = "thamso";
            columnExpression80.Table = table17;
            column80.Expression = columnExpression80;
            columnExpression81.ColumnName = "TenThamSo";
            columnExpression81.Table = table17;
            column81.Expression = columnExpression81;
            columnExpression82.ColumnName = "KieuThamSo";
            columnExpression82.Table = table17;
            column82.Expression = columnExpression82;
            columnExpression83.ColumnName = "GiaTri";
            columnExpression83.Table = table17;
            column83.Expression = columnExpression83;
            selectQuery17.Columns.Add(column80);
            selectQuery17.Columns.Add(column81);
            selectQuery17.Columns.Add(column82);
            selectQuery17.Columns.Add(column83);
            selectQuery17.Name = "thamso";
            selectQuery17.Tables.Add(table17);
            columnExpression84.ColumnName = "MaThuePhong";
            table18.Name = "thuephong";
            columnExpression84.Table = table18;
            column84.Expression = columnExpression84;
            columnExpression85.ColumnName = "MaPhong";
            columnExpression85.Table = table18;
            column85.Expression = columnExpression85;
            columnExpression86.ColumnName = "GioThuePhong";
            columnExpression86.Table = table18;
            column86.Expression = columnExpression86;
            columnExpression87.ColumnName = "GioTraPhong";
            columnExpression87.Table = table18;
            column87.Expression = columnExpression87;
            columnExpression88.ColumnName = "MaHoaDon";
            columnExpression88.Table = table18;
            column88.Expression = columnExpression88;
            selectQuery18.Columns.Add(column84);
            selectQuery18.Columns.Add(column85);
            selectQuery18.Columns.Add(column86);
            selectQuery18.Columns.Add(column87);
            selectQuery18.Columns.Add(column88);
            selectQuery18.Name = "thuephong";
            selectQuery18.Tables.Add(table18);
            columnExpression89.ColumnName = "MaTinhTrangPhong";
            table19.Name = "tinhtrangphong";
            columnExpression89.Table = table19;
            column89.Expression = columnExpression89;
            columnExpression90.ColumnName = "TinhTrangPhong";
            columnExpression90.Table = table19;
            column90.Expression = columnExpression90;
            selectQuery19.Columns.Add(column89);
            selectQuery19.Columns.Add(column90);
            selectQuery19.Name = "tinhtrangphong";
            selectQuery19.Tables.Add(table19);
            columnExpression91.ColumnName = "MaTrangThaiDatPhong";
            table20.Name = "trangthaidatphong";
            columnExpression91.Table = table20;
            column91.Expression = columnExpression91;
            columnExpression92.ColumnName = "TenTrangThaiDatPhong";
            columnExpression92.Table = table20;
            column92.Expression = columnExpression92;
            selectQuery20.Columns.Add(column91);
            selectQuery20.Columns.Add(column92);
            selectQuery20.Name = "trangthaidatphong";
            selectQuery20.Tables.Add(table20);
            columnExpression93.ColumnName = "MaTrangThaiThuePhong";
            table21.Name = "trangthaithuephong";
            columnExpression93.Table = table21;
            column93.Expression = columnExpression93;
            columnExpression94.ColumnName = "LoaiTrangThai";
            columnExpression94.Table = table21;
            column94.Expression = columnExpression94;
            selectQuery21.Columns.Add(column93);
            selectQuery21.Columns.Add(column94);
            selectQuery21.Name = "trangthaithuephong";
            selectQuery21.Tables.Add(table21);
            this.sqlDataSource1.Queries.AddRange(new DevExpress.DataAccess.Sql.SqlQuery[] {
            selectQuery1,
            selectQuery2,
            selectQuery3,
            selectQuery4,
            selectQuery5,
            selectQuery6,
            selectQuery7,
            selectQuery8,
            selectQuery9,
            selectQuery10,
            selectQuery11,
            selectQuery12,
            selectQuery13,
            selectQuery14,
            selectQuery15,
            selectQuery16,
            selectQuery17,
            selectQuery18,
            selectQuery19,
            selectQuery20,
            selectQuery21});
            this.sqlDataSource1.ResultSchemaSerializable = resources.GetString("sqlDataSource1.ResultSchemaSerializable");
            // 
            // HoaDon
            // 
            this.Bands.AddRange(new DevExpress.XtraReports.UI.Band[] {
            this.Detail,
            this.TopMargin,
            this.BottomMargin});
            this.ComponentStorage.AddRange(new System.ComponentModel.IComponent[] {
            this.sqlDataSource1});
            this.DataMember = "datphong";
            this.DataSource = this.sqlDataSource1;
            this.Version = "17.2";
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();

        }

        #endregion

        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.XRLabel xrLabel1;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
    }
}
